Lee-0210/Resonos_React

- resonos-app/src/containers/community/BoardContainer.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/CommunityController.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityServiceImpl.java
> 커뮤니티 백엔드 로직 수정

- resonos/src/main/java/com/cosmus/resonos/controller/community/MainPageController.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/BoardPostMapper.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityCategoryMapper.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/BoardPostService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/BoardPostServiceImpl.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityCategoryService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityCategoryServiceImpl.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/BoardPostMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityCategoryMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityMapper.xml
community -  글마다 좋아요, 댓글 수, 생성일, intro / 게시판 순위. 신설 게시판 - community로 변경 / search - type 기준으로 변경
> community -  글마다 좋아요, 댓글 수, 생성일, intro / 게시판 순위. 신설 게시판 - community로 변경 / search - type 기준으로 변경

- resonos-app/src/apis/auth.js
- resonos-app/src/components/Login/LoginForm.jsx
- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/community/Index.jsx
- resonos-app/src/components/community/card/BoardRankingCard.jsx
- resonos-app/src/components/community/card/PostListCard.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/BoardContainer.jsx
- resonos-app/src/contexts/LoginContextProvider.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/MainPageController.java
- resonos/src/main/java/com/cosmus/resonos/security/filter/JwtAuthenticationFilter.java
- resonos/src/main/java/com/cosmus/resonos/security/filter/JwtRequestFilter.java
> 자동 로그인 체크 안 하면 JWT 세션 쿠키化

- resonos-app/src/apis/community.js
- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/user/modal/TrackModalCommunity.jsx
- resonos-app/src/containers/community/BoardContainer.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/CommunityController.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityServiceImpl.java
> 매니저의 추천곡 변경 로직  完

- resonos/src/main/java/com/cosmus/resonos/controller/community/MainPageController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/BoardPost.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/Community.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityMapper.xml
[게시판 더보기 collection 적용](https://github.com/Lee-0210/Resonos_React/commit/96c04b9f98ebcd57b046f5c15433062ec6ea902c)
> 게시판 더보기 collection 적용

- resonos-app/src/apis/community.js
- resonos-app/src/components/Header/Header.jsx
- resonos-app/src/components/Login/LoginForm.css
- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/community/CommuSearch.jsx
- resonos-app/src/components/community/Index.jsx
- resonos-app/src/components/community/SearchMore.jsx
- resonos-app/src/components/community/card/MoreBoardCard.jsx
- resonos-app/src/components/community/card/PostListCard.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/components/user/Activity.jsx
- resonos-app/src/components/user/ActivityCommu.jsx
- resonos-app/src/containers/community/BoardContainer.jsx
- resonos-app/src/containers/community/IndexContainer.jsx
- resonos-app/src/containers/community/SearchContainer.jsx
- resonos-app/src/containers/community/SearchMoreContainer.jsx
- resonos-app/src/containers/user/ActivityContainer.jsx
- resonos-app/src/contexts/LoginContextProvider.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/CommunityController.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityMapper.xml
> 한줄소개 수정 로직 完

- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/community/style.css
> 게시글 작성 버튼 完

- resonos-app/src/apis/user.js
- resonos-app/src/components/Login/LoginForm.css
- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/community/card/MoreBoardCard.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/components/user/Activity.jsx
- resonos-app/src/components/user/ActivityCommu.jsx
- resonos-app/src/components/user/MypageTab.jsx
- resonos-app/src/components/user/card/AlbumReviewCard.jsx
- resonos-app/src/components/user/card/CommunityCard.jsx
- resonos-app/src/components/user/card/LikedAlbumReviewCard.jsx
- resonos-app/src/components/user/card/LikedTrackReviewCard.jsx
- resonos-app/src/components/user/card/TrackReviewCard.jsx
- resonos-app/src/containers/community/BoardContainer.jsx
- resonos-app/src/containers/user/ActivityContainer.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/user/UserController.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityMapper.xml
> 내 활동 페이지 진행中

- resonos/src/main/java/com/cosmus/resonos/controller/community/MainPageController.java
[pagination 정리](https://github.com/Lee-0210/Resonos_React/commit/7526e91ecc0b952fcd1b51c7a794fd16584e35c7)
> pagination 정리

- resonos-app/src/apis/user.js
- resonos-app/src/components/user/ActivityCommu.jsx
- resonos-app/src/components/user/card/BoardCard.jsx
- resonos-app/src/components/user/card/CommentCard.jsx
- resonos-app/src/components/user/card/PostCard.jsx
- resonos-app/src/components/user/section/BoardSection.jsx
- resonos-app/src/components/user/section/CommentSection.jsx
- resonos-app/src/components/user/section/PostSection.jsx
- resonos-app/src/containers/user/ActivityContainer.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/user/UserController.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/CommunityMapper.java
- resonos/src/main/java/com/cosmus/resonos/mapper/user/UserMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/CommunityService.java
- resonos/src/main/java/com/cosmus/resonos/service/user/UserService.java
- resonos/src/main/java/com/cosmus/resonos/service/user/UserServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/CommunityMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/user/UserMapper.xml
커뮤니티 활동 페이지 (좋아요한 게시글, 댓글 조회 제외) 完
> 커뮤니티 활동 페이지 (좋아요한 게시글, 댓글 조회 제외) 完

- resonos-app/src/components/community/Board.jsx
- resonos-app/src/components/community/card/PostListCard.jsx
- resonos-app/src/components/community/style.css
게시글 작성 버튼 위치 수정, 게시글 목록에서 게시판으로 이동가能
> 게시글 작성 버튼 위치 수정, 게시글 목록에서 게시판으로 이동가能

- resonos-app/src/components/user/PlaylistDetailForm.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/user/UserController.java
- resonos/src/main/java/com/cosmus/resonos/external/SpotifyApiClient.java
- resonos/src/main/java/com/cosmus/resonos/security/filter/JwtAuthenticationFilter.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/user/PlaylistMapper.xml
> 이제서야 알았다. notNullColumn

- resonos-app/src/containers/user/MypageContainer.jsx
- resonos-app/src/contexts/LoginContextProvider.jsx
> 로그아웃 시 헤더의 유저 정보 바로 없어지게 完

- resonos-app/src/App.css
- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/community/card/FreeVote.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/WYSIWYG.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/BoardPost.java
> 투표 데이터 컨트롤러에 넘기기 完

- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/community/card/FreeVote.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/WYSIWYG.jsx
> 투표 생성 UI 수정

- resonos-app/src/containers/community/WYSIWYG.jsx
> vote 리스트에서 객체로 변경 完

- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/ComVote.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/ComVoteArgumentMapper.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/VoteStatusMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/ComVoteService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/ComVoteServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/BoardPostMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/ComVoteArgumentMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/ComVoteMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/VoteStatusMapper.xml
> Yhm - vote - read, update 수정

- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/community/card/FreeVote.jsx
- resonos-app/src/containers/community/WYSIWYG.jsx
- resonos-app/src/contexts/LoginContextProvider.jsx
- resonos-app/src/pages/community/CreateUpdate.jsx
> 항목 content 요청 수정 完

- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/WYSIWYG.jsx
> 게시글 수정 데이터 보낼 준비 完

- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
- resonos/src/main/java/com/cosmus/resonos/controller/community/VoteStatusController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/VoteStatus.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/BoardPostMapper.java
- resonos/src/main/java/com/cosmus/resonos/mapper/community/VoteStatusMapper.java
- resonos/src/main/java/com/cosmus/resonos/service/community/BoardPostService.java
- resonos/src/main/java/com/cosmus/resonos/service/community/BoardPostServiceImpl.java
- resonos/src/main/java/com/cosmus/resonos/service/community/VoteStatusServiceImpl.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/BoardPostMapper.xml
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/VoteStatusMapper.xml
[vote 중복 투표 방지, return값 vote 객체](https://github.com/Lee-0210/Resonos_React/commit/7bd73ebe04a86e87d2c01c0337b98ab922be5bfb)
> Yhm vote 중복 투표 방지, return값 vote 객체

- resonos-app/src/components/community/Index.jsx
- resonos-app/src/components/community/Post.jsx
- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/community/post/PostContent.jsx
- resonos-app/src/components/community/post/PostTitle.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/WYSIWYG.jsx
- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/BoardPost.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/community/BoardPostMapper.xml
> 게시글 상세 디테일 수정, 매니저 권한 수정 完

- resonos-app/src/components/community/style.css
> 게시글 상세 페이지 CSS 修正

- resonos/src/main/resources/com/cosmus/resonos/mapper/community/BoardPostMapper.xml
community_name => name 으로 일괄 修正
> community_name => name 으로 일괄 修正

- resonos-app/src/components/community/card/DatePicker.jsx
> 최소 투표 종료일 현재 시간 + 3시간 完

- resonos-app/src/components/user/modal/TrackModal.jsx
- resonos-app/src/components/user/modal/TrackModalCommunity.jsx
- resonos-app/src/containers/community/WYSIWYG.jsx
> vote 객체를 아예 없애기 完

- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
- resonos/src/main/java/com/cosmus/resonos/controller/community/VoteStatusController.java
- resonos/src/main/java/com/cosmus/resonos/domain/community/ComVote.java
[투표 여부 vote 객체 내부로 이동](https://github.com/Lee-0210/Resonos_React/commit/1654610146482bdfa6ef0a8214098c91a2e2c336)
> Yhm - 투표 여부 vote 객체 내부로 이동

- resonos-app/src/containers/community/WYSIWYG.jsx
> useRef 처치 完

- resonos/src/main/java/com/cosmus/resonos/controller/community/BoardPostController.java
> Yhm - 관리자 글 삭제 임시

- resonos-app/src/components/community/Index.jsx
- resonos-app/src/components/community/post/CommentEdit.jsx
- resonos-app/src/components/community/style.css
- resonos/src/main/java/com/cosmus/resonos/controller/community/MainPageController.java
> CSS 수정 및 인기글 5 -> 7 完

- resonos-app/src/App.jsx
- resonos-app/src/components/admin/css/admin.module.css
- resonos-app/src/components/admin/toggle/ThemeToggle.jsx
- resonos-app/src/pages/community/Index.jsx
- resonos-app/src/styles/admin.css
Yhm - 커뮤니티 관리자 삭제, 수정 끝 및 색 반전
> Yhm - 커뮤니티 관리자 삭제, 수정 끝 및 색 반전

- resonos-app/src/components/admin/toggle/ThemeToggle.jsx
- resonos-app/src/styles/admin.css
[light-dark toggle header css 수정](https://github.com/Lee-0210/Resonos_React/commit/54ce92da7fc8b5dbca597cde3a8bbf4e77fee5ba)
> Yhm - light-dark toggle header css 수정

- resonos-app/src/components/Login/LoginForm.css
- resonos-app/src/components/admin/toggle/ThemeToggle.jsx
- resonos-app/src/components/community/Index.jsx
- resonos-app/src/components/community/style.css
- resonos-app/src/containers/community/IndexContainer.jsx
- resonos-app/src/index.css
> color 변수로 조금씩 수정 中

- resonos-app/src/components/Login/JoinForm.jsx
- resonos-app/src/components/community/Post.jsx
- resonos-app/src/components/community/card/DatePicker.jsx
- resonos-app/src/components/user/FollowArtist.jsx
- resonos-app/src/components/user/UserEditForm.jsx
- resonos-app/src/components/user/card/PostCard.jsx
- resonos-app/src/components/user/modal/TrackModal.jsx
- resonos-app/src/components/user/modal/TrackModalCommunity.jsx
- resonos-app/src/containers/community/IndexContainer.jsx
- resonos-app/src/containers/community/SearchContainer.jsx
- resonos-app/src/containers/community/SearchMoreContainer.jsx
- resonos-app/src/containers/user/ActivityContainer.jsx
- resonos-app/src/containers/user/BadgeContainer.jsx
- resonos-app/src/containers/user/FollowArtistContainer.jsx
- resonos-app/src/containers/user/FollowUserContainer.jsx
- resonos-app/src/containers/user/LikedMusicContainer.jsx
- resonos-app/src/containers/user/NotiContainer.jsx
- resonos-app/src/containers/user/PlaylistContainer.jsx
- resonos-app/src/containers/user/PlaylistDetailContainer.jsx
- resonos-app/src/containers/user/SetNotificationContainer.jsx
- resonos-app/src/contexts/LoginContextProvider.jsx
> console.log 주석 처리 및 수정 完

- resonos/src/main/resources/application.properties
> SNS 로그인 redirectURL 수정

- resonos-app/src/apis/admin.js
- resonos-app/src/components/admin/css/admin.module.css
- resonos-app/src/components/admin/first/MenuCard.jsx
- resonos-app/src/components/admin/second/CommunityCategoryList.jsx
- resonos-app/src/components/admin/second/CommunityIdCreate.jsx
- resonos-app/src/components/admin/second/MenuRows.jsx
- resonos-app/src/components/admin/second/ReportDetailPanel.jsx
- resonos-app/src/components/admin/second/SpotifySearchWithResults.jsx
- resonos-app/src/containers/admin/AdminAnPManageContainer.jsx
- resonos-app/src/containers/admin/AdminContainer.jsx
- resonos-app/src/containers/admin/AdminQnAContainer.jsx
- resonos-app/src/styles/admin.css
- resonos-app/vite.config.js
- resonos/SQL/9.17-api테이블 수정 .sql
- resonos/SQL/9.17-테이블 수정 .sql
- resonos/src/main/java/com/cosmus/resonos/domain/admin/ExternalApiConfig.java
- resonos/src/main/java/com/cosmus/resonos/external/SpotifyApiClient.java
- resonos/src/main/java/com/cosmus/resonos/service/review/YouTubeApiService.java
- resonos/src/main/resources/com/cosmus/resonos/mapper/admin/ExternalApiConfigMapper.xml
Yhm - css, 음악데이터 확인 모뎀, qna 카테고리 id 생성 폼 추가
> Yhm - css, 음악데이터 확인 모뎀, qna 카테고리 id 생성 폼 추가
